name: KBase Workspace tests

on:
  pull_request:
    types:
    - opened
    - reopened
    - synchronize
    - ready_for_review
  push:
    # run workflow when merging to main or develop
    branches:
      - main
      - master
      - develop

jobs:

  shock_java_client_tests:
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        include:
          - java: '8'
            mongo: 'mongodb-linux-x86_64-3.6.13'
          - java: '11'
            mongo: 'mongodb-linux-x86_64-3.6.13'

    steps:
      - uses: actions/checkout@v3

      - name: Set up java
        uses: actions/setup-java@v3
        with:
          distribution: 'temurin'
          java-version: ${{matrix.java}}

      - name: Install dependencies and set up test config
        shell: bash
        run: |
          export HOMEDIR=`pwd`

          # set up shock
          export SHOCKEXE=$HOMEDIR/shock_java_client/shock_builds/kbase_fork/160815_e9f0e1618e265042bf5cb96429995b5e6ec0a06a/shock-server

          # move to parent dir of homedir to install binaries etc
          cd ..
          
          # set up jars
          git clone https://github.com/kbase/jars
          export JARSDIR=$(pwd)/jars/lib/jars/

          # set up mongo
          wget -q http://fastdl.mongodb.org/linux/${{matrix.mongo}}.tgz
          tar xfz ${{matrix.mongo}}.tgz
          export MONGOD=`pwd`/${{matrix.mongo}}/bin/mongod

          # set up test config
          cd $HOMEDIR
          cp test/test.cfg test/test-actual.cfg
          sed -i "s#^test.jars.dir.*#test.jars.dir=$JARSDIR#" test-actual.cfg
          sed -i "s#^test.mongo.exe.*#test.mongo.exe=$MONGOD#" test-actual.cfg
          sed -i "s#^test.shock.exe.*#test.shock.exe=$SHOCKEXE#" test-actual.cfg
          cat test.cfg

      - name: Run tests
        shell: bash
        run: |
          make test TESTCFG=test-actual.cfg

# TODO COVERAGE - ant doesn't do coverage right now, just do it when gradle works
